/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'id' : bigint,
  'title' : string,
  'author' : string,
  'sales' : bigint,
  'price' : number,
  'royaltyPerSale' : number,
}
export interface _SERVICE {
  'addBook' : ActorMethod<[string, string, number, bigint, number], bigint>,
  'deleteBook' : ActorMethod<[bigint], boolean>,
  'getBooks' : ActorMethod<[], Array<Book>>,
  'getStats' : ActorMethod<
    [],
    { 'totalSales' : bigint, 'totalRoyalties' : number, 'totalBooks' : bigint }
  >,
  'updateBook' : ActorMethod<
    [bigint, string, string, number, bigint, number],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];