/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Book = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'author' : IDL.Text,
  'sales' : IDL.Nat,
  'price' : IDL.Float64,
  'royaltyPerSale' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addBook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'deleteBook' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalSales' : IDL.Nat,
          'totalRoyalties' : IDL.Float64,
          'totalBooks' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'updateBook' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Float64],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Book = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'author' : IDL.Text,
    'sales' : IDL.Nat,
    'price' : IDL.Float64,
    'royaltyPerSale' : IDL.Float64,
  });
  
  return IDL.Service({
    'addBook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'deleteBook' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalSales' : IDL.Nat,
            'totalRoyalties' : IDL.Float64,
            'totalBooks' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'updateBook' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Float64],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };